### ISSUE TITLE
Integrate pycodestyle

### ISSUE THREAD

**Issue by peter279k** [peter279k/today-co#10]
It should be good to integrate this [tool ](https://pypi.org/project/pycodestyle/)to do Python coding style check.

And it can also be integrated on CI build.

**Comment by youmu257** [comment]
Is the issue means add git pre-commit hook to check coding style?

**Comment by peter279k** [comment]
This issue is part of stuff on CI build.

Here is a sample about using [Travis CI build](https://qiita.com/liseos_x140/items/28a7dd835d28612f6d29#travisyml) to integrate coding style with `pycodestyle`.

**Comment by peter279k** [comment]
Closed via PR #11.
